### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Dangxc** [MiracleHH/RecommPoison#2]
当运行攻击ml-1m数据集时出现bug:Traceback (most recent call last):
  File "D:/Project/RecommPoison-main/attacks/main.py", line 224, in <module>
    target_hr=get_single_HR(poison_model,num_users,target_users,unrated_items,target_item,topK,device)
  File "D:\Project\RecommPoison-main\attacks\evaluate.py", line 62, in get_single_HR
    ratings=model(torch.LongTensor([user]*len(negative_reference[user])).to(device),torch.LongTensor(negative_reference[user]).to(device))
IndexError: list index out of range
Process finished with exit code 1.

请问如何解决这里的错误呢：IndexError: list index out of range，期待回复。

**Comment by MiracleHH** [comment]
> 当运行攻击ml-1m数据集时出现bug:Traceback (most recent call last): File "D:/Project/RecommPoison-main/attacks/main.py", line 224, in target_hr=get_single_HR(poison_model,num_users,target_users,unrated_items,target_item,topK,device) File "D:\Project\RecommPoison-main\attacks\evaluate.py", line 62, in get_single_HR ratings=model(torch.LongTensor([user]*len(negative_reference[user])).to(device),torch.LongTensor(negative_reference[user]).to(device)) IndexError: list index out of range Process finished with exit code 1.
> 
> 请问如何解决这里的错误呢：IndexError: list index out of range，期待回复。

Hi @Dangxc, thanks for your interest in our work!

Based on the given error information, it seems that the ID number of the user has exceeded the length of `negative_reference` list. I guess the reason is that you have not guaranteed that both the IDs of users and items start from 0  (instead of 1) before splitting the dataset.  You can refer to the [dataset requirements](https://github.com/MiracleHH/RecommPoison/tree/main/data_processing#dataset-requirements) for more details on pre-processing the original dataset. Thanks!
